# todo: spin our own image
image: jamwaffles/circleci-embedded-graphics:1.40.0-3

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test